### ISSUE TITLE
protocol.buddycloud.com continually connecting

### ISSUE THREAD

**Issue by gittigger** [buddycloud/buddycloud-tests-framework#21]
I commented on https://github.com/buddycloud/buddycloud-tests-framework/issues/12 but couldn't see how to reopen, so opening this one. When I try to use protocol.buddycloud.com it gets to the buddycloud discovery test but fails. I then see it continually trying to connect for a long time with following message in prosody logs, repeated every 2 seconds or so:

Jul 26 00:31:38 c2s211be60 info Client connected
Jul 26 00:31:38 c2s211be60 info c2s stream for closed: This server does not serve buddycloud.org
Jul 26 00:31:38 c2s211be60 info Client disconnected: connection closed

Can we make it stop after a few attempts please?

**Comment by thanh-nguyen-van** [comment]
Hello, 
I have the same issue, while I test on localhost using `curl -X POST -H "authorization:Basic anVsaWV0QGJ1ZGR5Y2xvdWQuY29tOnJvbWVvLWZvcmV2ZXI="   -d '{ "username": "jm.jimenez2", "password": "m@abc.com"}' http://localhost:9123/api/account`

I got the message (I'm using production environment in docker container)

> "message": "Session error: <stream:error xmlns:stream=\"http://etherx.jabber.org/streams\"><host-unknown xmlns=\"urn:ietf:params:xml:ns:xmpp-streams\"/><text xmlns=\"urn:ietf:params:xml:ns:xmpp-streams\">This server does not serve buddycloud.com</text>/stream:error"
> }

Please give me an advice ! THX
